//HOME
export const SET_FIRST_USE = "SET_FIRST_USE";
export const LOAD_WALLET_NAME = "LOAD_WALLET_NAME";
export const LOAD_TOTAL_AMOUNT = "LOAD_TOTAL_AMOUNT";
export const SET_ANCHOR_EL = "SET_ANCHOR_EL";
export const SET_OPEN_DIALOG = "SET_OPEN_DIALOG";
export const SET_MODIFY_OPEN_DIALOG = "SET_MODIFY_OPEN_DIALOG";
export const SET_TOTAL_AMOUNT = "SET_TOTAL_AMOUNT";
export const SET_NEW_NAME = "SET_NEW_NAME";
export const SET_RENAME_DIALOG = "SET_RENAME_DIALOG";
export const SET_SNACKBAR_OPEN = "SET_SNACKBAR_OPEN";

//HISTORY
export const PUSH_RECORD = "PUSH_RECORD";