//HOME
export const SET_FIRST_USE = "SET_FIRST_USE";
export const LOAD_TOTAL_AMOUNT = "LOAD_TOTAL_AMOUNT";
export const SET_ANCHOR_EL = "SET_ANCHOR_EL";
export const SET_OPEN_DIALOG = "SET_OPEN_DIALOG";
export const SET_MODIFY_OPEN_DIALOG = "SET_MODIFY_OPEN_DIALOG";